pr remark: look for rejected deps as well

diff --git a/.github/workflows/verify.yaml b/.github/workflows/verify.yaml
--- a/.github/workflows/verify.yaml
+++ b/.github/workflows/verify.yaml
@@ -75,8 +75,16 @@ jobs:
         run: |
           # dash returns a nonzero exit code if there are libs that need review. the "|| true" avoids that
           ./gradlew allDependencies | grep -Poh "(?<=\s)[\w.-]+:[\w.-]+:[^:\s\[\]]+" | sort | uniq | java -jar dash.jar - -summary DEPENDENCIES-gen || true
+          
+          # log warning if restricted deps are found
           grep -E 'restricted' DEPENDENCIES | if test $(wc -l) -gt 0; then 
             echo "::warning file=DEPENDENCIES,title=Restricted Dependencies found::Some dependencies are marked 'restricted' - please review them" 
+          fi
+          
+          # log error and fail job if rejected deps are found
+          grep -E 'rejected' DEPENDENCIES | if test $(wc -l) -gt 0; then
+            echo "::error file=DEPENDENCIES,title=Rejected Dependencies found::Some dependencies are marked 'rejected', they cannot be used"
+            exit 1
           fi
       - name: Check for differences
         run: |
